version: 2
jobs:
  build:
    # working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx1536m -XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: |
            sudo chmod +x ./gradlew
            ./gradlew androidDependencies
      - run:
          name: Build
          command: |
              if should_be_release; then
                  ./gradlew --offline --stacktrace assembleRelease
              else
                  ./gradlew --offline --stacktrace assemble${APP_BUILD_TYPE^}
              fi

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk

# workaround for tag trigger
# because workflow git tag trigger does not work well
deployment:
  fake_for_deploy:
    tag: /.*/
    commands:
      - echo "make tags run in 2.0"
